mcpServer:
  docker:
    serverName : "docker-server"
    serverVersion: "1.0.0"

  file:
    serverName : "file-server"
    serverVersion: "1.0.0"

  llm:
    serverName : "llm-server"
    serverVersion: "1.0.0"

llm:
  gemini:
    apikey: "${GOOGLE_API_KEY}"
    model: "gemini-2.0-flash"